spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ceos21
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
